name: Test

on:
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . -t test:dev
      - name: Show the image
        run: docker images ps -a
      - name: Build the second Docker image
        run: |
          sed -i 's/requirements.txt/requirements_dev.txt/g' Dockerfile
          docker build . -t test:dev-2
      - name: Show the second image
        run: docker images ps -a
  
  test-envd:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Set envd
       run: |
         pip3 install --pre --upgrade envd
         envd bootstrap
     - name: Build the image using envd
       run: envd build -t test:dev
     - name: Show the image
       run: docker images ps -a

     - name: Build the second image using envd
       run: |
         sed -i 's/requirements.txt/requirements_dev.txt/g' build.envd
         envd build -t test:dev-2
     - name: Show the second image
       run: docker images ps -a